config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, 
    controllers: { sessions: "admin/sessions" }, 
    path: 'admin', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout'
    }

  scope path: "/(:prefix)", :module => 'admin', :as => 'admin', constraints: { host: UrlHelper.host_constraint(:admin), prefix: 'admin' } do 

    post 'position' => 'application#set_position', as: :set_position
    post 'positions' => 'application#set_positions', as: :set_positions

    resources :puzzles, :path => 'puzzles/pack', except: [:index]
    delete 'puzzles/puzzle_asset/:id', to: 'puzzles#delete_puzzle_asset', as: :delete_puzzle_asset # check this

    resources :languages, except: [:index]
    get 'config' => 'config#index', as: :config
    get 'config/edit/:parameter' => 'config#edit', as: :config_edit
    patch 'config/edit/:parameter' => 'config#update', as: :config_update

    scope :puzzles do

      resources :packs do
        get 'toggle_published' => 'packs#toggle_published', as: :toggle_published
        get 'get_quality' => 'packs#get_quality', as: :get_quality
        get 'import_data/(:mode)' => 'packs#import_data', as: :import_data
        get 'import_images' => 'packs#import_images', as: :import_images
        get 'relink_google_sheet' => 'packs#relink_google_sheet', as: :relink_google_sheet
        get 'ping' => 'packs#check_imports', as: :ping
        get 'info' => 'packs#get_pack_info', as: :info
        get 'restore' => 'packs#restore_from_published', as: :restore_from_published
        resources :puzzle_assets, :path => 'assets', except: [:index]
      end

      scope :packs do
        post '/search' => 'packs#search', as: :search_puzzles
        get '/create_packs/:type/:number' => 'packs#create_packs', as: :create_packs
      end

      get 'puzzle_assets' => 'puzzle_assets#index', as: :puzzle_assets

      get 'generate_sprite_sheets' => 'packs#generate_sprite_sheets', as: :generate_sprite_sheets

      get 'import_data/:puzzle_id/(:mode)' => 'puzzles#import_data', as: :import_puzzle_data

      get 'apitest' => 'api_tester#index', as: :api_test

      post 'move' => 'puzzles#move', as: :puzzle_move

      get 'multi_toggle_published' => 'packs#multi_toggle_published', as: :multi_toggle_published
      get 'multi_import_data' => 'packs#multi_import_data', as: :multi_import_data
      get 'multi_import_images' => 'packs#multi_import_images', as: :multi_import_images

    end

    post 'update_pack' => 'puzzles#create_remote', as: :pack_remote
    post 'update_pack/remove_extras' => 'puzzles#create_remote_and_remove_extras', as: :pack_remote_remove_extras
    post 'update_puzzle' => 'puzzles#create_remote_puzzle', as: :pack_puzzle_remote

    get 'export_answers/:lang/(:pack_type)' => 'puzzles#export_answers', as: :export_answers
    
    get 'job_status/' => 'jobs#index', as: :jobs_status
    
    get '/auth/:provider/callback', to: 'twitter#auth'

    root 'packs#index'

  end

  scope path: "/(:prefix)", constraints: { host: UrlHelper.host_constraint(:data), prefix: 'data' } do 

    get ':api_version/puzzle(.:format)' => 'data#user_generated_puzzle', as: :user_generated_puzzle
    get ':api_version/packs_list(.:format)' => 'data#pack_list', as: :pack_get_list
    get ':api_version/packs_list_chinese(.:format)' => 'data#pack_list_chinese', as: :pack_get_list_chinese
    get ':api_version/packs/puzzle(.:format)' => 'data#pack_puzzle', as: :pack_get_puzzle
    get ':api_version/get_date' => 'data#get_server_date', as: :get_date
    get ':api_version/daily_puzzle(.:format)' => 'data#dailypuzzle', as: :daily_puzzle

  end

  root to: proc { [404, {}, ['']] }

end

app/controllers/admin/packs_controller.rb
class Admin::PacksController < Admin::ApplicationController
  include UrlHelper
  include AdminHelper
  
  before_action :admin_auth_level_only!
  before_action :set_parent_breadcrumb
  before_action :get_multi_ids, only: [:multi_import_images, :multi_toggle_published, :multi_import_data]
  after_action :flash_notice, :only => [:update, :create]
  after_action :refresh_pack_zip, :only => [:update, :create, :destroy]
  after_action :refresh_game_positions, :only => [:update, :create, :destroy]

  def index
    @packs = Pack.filtered params[:filter]
    @invalid_packs = Pack.invalid
    get_languages
    get_cookies
  end

  def new
    @pack = Pack.new
    @url = admin_packs_path
    add_breadcrumb 'New Puzzle Pack'
  end

  def create
    
    @pack = Pack.new pack_params

    if @pack.save
      clear_cache
      redirect_to params[:edit] ? edit_admin_pack_path(id: @pack.id) : admin_packs_path
    else
      flash.now[:errors] = @pack.errors.full_messages
      render action: 'new'
    end
  end

  def edit

    begin
      @pack = Pack.find params[:id]
    rescue
      return redirect_to admin_root_path
    end

    @url = admin_pack_path(id: @pack.id)

    get_languages
    get_cookies

    add_breadcrumb @pack.pack_code
    
  end

  def update

    begin
      @pack = Pack.find params[:id]
    rescue
      return redirect_to admin_root_path
    end

    if @pack.update_attributes(pack_params)
      
      @pack.update_status_column
      clear_cache
      redirect_to params[:edit] ? edit_admin_pack_path(id: @pack.id) : admin_packs_path
      
    else
      
      @url = admin_pack_path(id: @pack.id)
      flash.now[:errors] = @pack.errors.full_messages
      render action: 'edit'

    end

  end

  def destroy

    begin
      @pack = Pack.find params[:id]
    rescue
      return redirect_to admin_root_path
    end
    
    if @pack.destroy
      redirect_to admin_packs_path
    else
      flash.now[:errors] = @pack.errors.full_messages
      render action: 'edit'
    end

  end

  def toggle_published

    @pack = Pack.find params[:pack_id]

    if @pack.is_publishable

      @pack.published = !@pack.published
      @pack.save
      
      @pack.update_status_column
      
      @pack.delayed_parcel_process

    end
    
    redirect_to edit_admin_pack_path(id: @pack.id)

  end

  def get_quality

    get_languages

    pack = Pack.find params[:pack_id]
    config = AppConfig.get

    quality = @languages.collect do |language|
      pack.quality(language.code)
    end

    render :json => {
      quality: quality,
      quality_threshold_1: config.quality_threshold_1,
      quality_threshold_2: config.quality_threshold_2
    }

  end

  def import_data

    @pack = Pack.find params[:pack_id]
    @pack.delayed_data_import params[:content], params[:language]

    redirect_to edit_admin_pack_path(id: @pack.id)

  end

  def import_images

    @pack = Pack.find params[:pack_id]
    @pack.delayed_images_import

    redirect_to edit_admin_pack_path(id: @pack.id)

  end

  def restore_from_published

    restored = 0

    @pack = Pack.find params[:pack_id]

    @pack.pack_puzzles.each do |puzzle|
      
      if !puzzle.puzzle_published.blank?
        puzzle.update_column(:puzzle, puzzle.puzzle_published)
        restored = restored + 1
      end

    end

    flash[:notices] = ["Restored #{restored} puzzles"]

    @pack.update_status_column
    @pack.update_modified_at_time

    redirect_to edit_admin_pack_path(id: @pack.id)

  end

  def multi_import_images

    if @packs
      
      @packs.each do |pack|
        pack.delayed_images_import
      end

      flash[:notices] = ["Importing images for #{@packs.length} packs"]

    end

    redirect_to admin_packs_path

  end

  def multi_toggle_published

    published = 0
    unpublished = 0

    if @packs
      
      @packs.each do |pack|

        if pack.is_publishable

          pack.published = !pack.published
          pack.save

          published = published + 1 if pack.published
          unpublished = unpublished + 1 if !pack.published
          
          pack.update_status_column
          pack.delayed_parcel_process

        end

      end

      flash[:notices] = ["#{published} published, #{unpublished} unpublished"]

    end

    redirect_to admin_packs_path

  end

  def multi_import_data

    if @packs
      
      @packs.each do |pack|
        pack.delayed_data_import params[:content], params[:language]
      end

      flash[:notices] = ["Importing data for #{@packs.length} packs"]

    end

    redirect_to admin_packs_path

  end

  def check_imports

    @pack = Pack.find params[:pack_id]

    render :json => { 
      data_processing: @pack.data_processing,
      images_processing: @pack.images_processing,
      parcel_processing: @pack.parcel_processing,
      draft_parcel_processing: @pack.draft_parcel_processing
    }

  end

  def get_pack_info

    @pack = Pack.find params[:pack_id]
    puzzles = @pack.pack_puzzles.collect do |p|
      {
        id: p.id, 
        image_id: p.image_id, 
        position: p.position
      }
    end

    render :json => {
      puzzles: puzzles
    }

  end

  def generate_sprite_sheets
    PackOps.set_sprite_sheet_status 'refreshing'
    PackOps.delay.generate_all_sprite_sheets
    redirect_to admin_packs_path
  end

  def search

    if params[:q]
      @searched = params[:q]
      @pack_puzzles = PackPuzzle.search(@searched)
      @invalid_packs = Pack.invalid
      @languages = Language.all
    end

    render action: 'index'

  end

  def create_packs

    if [Pack::TYPE_DAILY, Pack::TYPE_CLASSIC, Pack::TYPE_CHINESE, Pack::TYPE_SPECIAL].include?(params[:type])
      
      number = params[:number].to_i
      
      if [1, 10].include?(number)
        
        PackOps.bulk_create_packs(params[:type], number)

        flash[:notices] = ["#{number} #{params[:type]} pack #{number > 1 ? 's' : ''} created"]

      end

    end

    redirect_to admin_packs_path

  end

  def relink_google_sheet

      @pack = Pack.find params[:pack_id]
      result = DataImporter.relink_to_google_sheet @pack

      if result
        flash[:notices] = ["Successfully relinked to Google Sheets"]
      else
        flash[:notices] = ["Unable to relink to Google Sheets"]
      end

      redirect_to edit_admin_pack_path(id: @pack.id)
      
  end

  private

  def set_parent_breadcrumb
    add_breadcrumb 'Puzzle Packs', admin_packs_path
  end

  def pack_params
    params.require(:pack).permit :pack_code, :extra_data, :tested_primary, :published, :required_app_version, pack_puzzle_positions: []
  end

  def flash_notice
    if !@pack.flash_alert.blank?
      flash[:errors] = [@pack.flash_alert]
    end
  end

  def get_multi_ids
    
    ids = params[:ids].split(',').collect(&:to_i)
    
    if ids.length > 0
      @packs = Pack.where(id: ids)
    else
      @packs = nil
    end

  end

end

app/views/admin/packs/_grid_item.slim
- if puzzle.pack.tested_primary
  - is_invalid = puzzle.status_missing_locales || puzzle.status_invalid
- else
  - is_invalid = puzzle.status_invalid

.puzzle-item.sort-item data-id=puzzle.id class="#{is_invalid ? 'invalid' : ''}"
  
  .panel.panel-default

    .panel-heading 
      strong
        .label.label-default = puzzle.game_position_or_date
        = raw "&nbsp;&nbsp;"
        = puzzle.image_id

      .puzzle-actions
        a.fa.fa-pencil-square-o data-toggle="tooltip" data-placement="top" title="Edit Pack Puzzle" href=edit_admin_puzzle_path(id: puzzle.id)
        a.fa.fa-code data-toggle="tooltip" data-placement="top" title="View Pack Puzzle JSON" href=admin_puzzle_path(id: puzzle, format: :json) target="_blank"

    .panel-body
      .row

        .col-sm-6

          - if puzzle.puzzle_asset && !puzzle.puzzle_asset.image_reprocessing && puzzle.puzzle_asset.image.attached?
            = image_tag puzzle.puzzle_asset.image.variant(resize_to_limit: [100, 100])
          - else
            img.thumbnail-image src=asset_path('transparent.gif')

          .language-quality
            - @languages.each do |language|
              = raw pretty_quality(puzzle.quality(language.code))
            = raw "&nbsp;"

        .col-sm-6

          = raw puzzle.display_answers.join('<br/>')

      - caption = raw puzzle.caption(Language::CODE_ENGLISH)
      - if caption
        .row.caption-row
          .col-sm-12
              strong = raw puzzle.caption(Language::CODE_ENGLISH)

app/views/admin/packs/edit.slim
= form_for [:admin, @pack], html: {}, url: @url do |f|

  .row.form-actions
    .col-md-8.pack-title

      h2 
        span = @pack.pack_code

        .label class="label-#{status_class(@pack.status)}" = status_human(@pack.status)
    
    .col-md-4

      .btn-group
        - prev_url = prev_pack_url(@pack)
        - next_url = next_pack_url(@pack)
        a.btn.btn-default disabled=(!prev_url) href=prev_url = raw "&lt;"
        a.btn.btn-default disabled=(!next_url) href=next_url = raw "&gt;"

      .btn-group
        = f.submit 'Save', class: 'btn btn-default'

        button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
          span.caret
          span.sr-only Toggle Dropdown
        ul.dropdown-menu.pull-right role="menu"
          li 
            a.save-edit href="#" Save and Edit
          li 
            a href=admin_pack_relink_google_sheet_path(pack_id: @pack)
              | Re-link to Google Sheets
          li
            a href="#{admin_packs_path}" Cancel
          - unless @pack.new_record? 
            li.divider
            li= link_to 'Delete', admin_pack_path(id: @pack), method: :delete, data: { confirm: "Are you sure you want to delete this pack?" }

  .row.pack-actions data-ping-url=admin_pack_ping_path(pack_id: @pack.id)
    .col-md-12
      .btn-group

        - klass = @pack.is_publishable ? '' : 'disabled'
        - title = @pack.status == Pack::STATUS_PUBLISHED ? 'Unpublish' : 'Publish'
        - href = @pack.is_publishable ? admin_pack_toggle_published_path(pack_id: @pack.id) : '#'

        a.btn.btn-default class=klass href=href
          span = title


        .btn-group
          - href = @pack.data_processing ? '#' : admin_pack_import_data_path(pack_id: @pack.id)

          - if !@pack.data_processing

            button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
              = image_tag 'icon-drive.png', size: "18x18"
              = "Sync data "
              span.caret
              span.sr-only Toggle Dropdown
            ul.dropdown-menu role="menu"
              li
                a href=href class="#{@pack.has_layouts ? 'confirm-action' : ''}" data-confirm-msg="This pack has layouts - really sync the data and destroy them?"
                  = "Sync data"
              li
                a.selective-sync type="button" data-toggle="modal" data-target="#selective-sync-modal"
                  = "Sync data (SELECTIVE)"

          - else

            .btn.btn-default class="disabled" data-ping="data_processing"
              = image_tag 'icon-drive.png', size: "18x18"
              = "Data syncing ..."


        - klass = @pack.images_processing ? 'disabled' : ''
        - title = @pack.images_processing ? 'Images syncing ...' : 'Sync images'
        - href = @pack.data_processing ? '#' : admin_pack_import_images_path(pack_id: @pack.id)

        a.btn.btn-default class=klass href=href data-ping="#{@pack.images_processing ? 'images_processing' : ''}"
          = image_tag 'icon-dropbox.png', size: "18x18"
          span = title

        
        - attached = @pack.pack_parcel.attached?
        - klass = @pack.parcel_processing || !attached ? 'disabled' : ''
        - title = @pack.parcel_processing ? 'Published zip processing ...' : (attached ? 'Download published zip' : 'No published zip')
        - href = !@pack.parcel_processing && attached ? rails_storage_proxy_url(@pack.pack_parcel) : '#'

        a.btn.btn-default class=klass href=href data-ping="#{@pack.parcel_processing ? 'parcel_processing' : ''}"
          = image_tag 'icon-zip.png', size: "18x18"
          span = title
        
        - attached = @pack.draft_pack_parcel.attached?
        - klass = @pack.draft_parcel_processing || !attached ? 'disabled' : ''
        - title = @pack.draft_parcel_processing ? 'Draft zip processing ...' : (attached ? 'Download draft zip' : 'No draft zip')
        - href = !@pack.draft_parcel_processing && attached ? rails_storage_proxy_url(@pack.draft_pack_parcel) : '#'

        a.btn.btn-default class=klass href=href data-ping="#{@pack.draft_parcel_processing ? 'draft_parcel_processing' : ''}"
          = image_tag 'icon-zip.png', size: "18x18"
          span = title

        - klass = @pack.worksheet_url ? '' : 'disabled'
        - href = @pack.worksheet_url ? @pack.worksheet_url : '#'
        - target = @pack.worksheet_url ? '_blank' : '_self'
        a.btn.btn-default class=klass href=href target=target
          = image_tag 'icon-sheets.png', size: "18x18"
          span View in Google Sheets

        a.btn.btn-default.confirm-action data-confirm-msg="Really restore this pack from published?" href=admin_pack_restore_from_published_path(pack_id: @pack.id) Restore from published

  .asset-thumbnails

    - if @pack.pack_puzzles.length == 0 && @pack.orphaned_assets.length == 0
      .col-sm-6 
        p No puzzles yet

    - @pack.pack_puzzles.each do |puzzle|
      = render partial: 'grid_item', locals: {puzzle: puzzle, orderable: true}

    - @pack.orphaned_assets.each do |puzzle_asset|

      .puzzle-item

        .panel.panel-default

          .panel-heading 
            = puzzle_asset.image_id
            br
            = puzzle_asset.id

            .puzzle-actions
              = link_to '', admin_delete_puzzle_asset_path(id: puzzle_asset.id), method: :delete, class: 'fa fa-trash-o', data: { confirm: "Are you sure you want to delete this asset?" }

          .panel-body.row
            .col-sm-6
              .thumbnail.placeholder
                img src=asset_path(puzzle_asset.image(:thumbnail))


  .row.form-group
    .col-sm-6
      a type="button" class="btn btn-default" href="#{new_admin_puzzle_path(pack_id: @pack.id)}"
        = "New Puzzle"

  .row.form-group

    .col-sm-3
      = f.check_box :tested_primary
      | &nbsp;&nbsp;&nbsp;&nbsp;
      = f.label :tested_primary, 'Tested Primary Language', class: 'control-label'

  .row.form-group
    .col-sm-4
      = f.label :extra_data, class: 'control-label'
      = f.text_area :extra_data, class: 'form-control', rows: 6

  - if @pack.is_daily || @pack.is_special
    .row
      .form-group.col-sm-4
        = f.label :required_app_version, class: 'control-label'
        = f.text_field :required_app_version, class: 'form-control'

= render partial: 'admin/shared/modal_sync'

app/views/admin/packs/index.slim
- invalid_packs = @invalid_packs.collect(&:pack_code).join(',')
- config = AppConfig.get

.row.packs-search-row
  .col-sm-12

    form action=admin_search_puzzles_path method="post"

      .input-group.input-group-lg.search-puzzles

        input.form-control type="text" class="" name="q" placeholder="Search Pack Puzzles" value=@searched

        span.input-group-btn
          input.btn.btn-default type="submit" Search

.row.packs-button-row
  
  .col-sm-6
    .btn-group

      .btn.btn-default
        - if params[:filter] == Pack::TYPE_CLASSIC
          | Classic Packs
        - elsif params[:filter] == Pack::TYPE_CHINESE
          | Chinese Packs
        - elsif params[:filter] == Pack::TYPE_DAILY
          | Daily Packs
        - elsif params[:filter] == Pack::TYPE_SPECIAL
          | Special Packs
        - else
          | All Packs


      button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
        span.caret
        span.sr-only Toggle Dropdown
      
      ul.dropdown-menu.pack-type-dropdown role="menu"
        li 
          a href="#{admin_packs_path}" All Packs
        li 
          a href="#{admin_packs_path}?filter=#{Pack::TYPE_CLASSIC}" Classic Packs
        li 
          a href="#{admin_packs_path}?filter=#{Pack::TYPE_CHINESE}" Chinese Packs
        li 
          a href="#{admin_packs_path}?filter=#{Pack::TYPE_DAILY}" Daily Packs
        li 
          a href="#{admin_packs_path}?filter=#{Pack::TYPE_SPECIAL}" Special Packs

    | &nbsp;&nbsp;
    .btn-group

      .btn.btn-default
        | Export Answers


      button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
        span.caret
        span.sr-only Toggle Dropdown
      
      ul.dropdown-menu.language-dropdown role="menu"
        - Language.all.each do |lang|
          li 
            a href="#{admin_export_answers_path(lang: lang.code, pack_type: params[:filter], format: 'csv')}" = lang.name

    - if @config.sprite_sheet_status == 'stale'
      | &nbsp;&nbsp;
      a.btn.btn-default href=admin_generate_sprite_sheets_path
        | Regenerate thumbnails
    
    - elsif @config.sprite_sheet_status == 'refreshing'
      | &nbsp;&nbsp;
      a.btn.btn-default disabled="disabled" href="#"
        | Thumbnails refreshing ...

    - elsif @config.puzzle_sheets.exists?
      | &nbsp;&nbsp;
      a.btn.btn-default href=@config.puzzle_sheets(:original)
        = image_tag 'icon-download.png', size: "18x18"
        | Download Sprite Sheets

  .col-sm-6

    .btn-group.bulk-create-packs

      a.btn.btn-default href=new_admin_pack_path New Pack

      button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
        span.caret
        span.sr-only Toggle Dropdown
      
      ul.dropdown-menu.pull-right role="menu"
        li 
          a data-number="1" data-type=Pack::TYPE_CLASSIC href=admin_create_packs_path({type: Pack::TYPE_CLASSIC, number: 1}) Next Classic pack
        li 
          a data-number="10" data-type=Pack::TYPE_CLASSIC href=admin_create_packs_path({type: Pack::TYPE_CLASSIC, number: 10}) 10 Classic packs
        li 
          a data-number="1" data-type=Pack::TYPE_DAILY href=admin_create_packs_path({type: Pack::TYPE_DAILY, number: 1}) Next Daily pack
        li 
          a data-number="10" data-type=Pack::TYPE_DAILY href=admin_create_packs_path({type: Pack::TYPE_DAILY, number: 10}) 10 Daily packs
        li 
          a data-number="1" data-type=Pack::TYPE_CHINESE href=admin_create_packs_path({type: Pack::TYPE_CHINESE, number: 1}) Next Chinese pack
        li 
          a data-number="10" data-type=Pack::TYPE_CHINESE href=admin_create_packs_path({type: Pack::TYPE_CHINESE, number: 10}) 10 Chinese packs
        li 
          a data-number="1" data-type=Pack::TYPE_SPECIAL href=admin_create_packs_path({type: Pack::TYPE_SPECIAL, number: 1}) Next Special pack
        li 
          a data-number="10" data-type=Pack::TYPE_SPECIAL href=admin_create_packs_path({type: Pack::TYPE_SPECIAL, number: 10}) 10 Special packs

- if @packs

  div
    table.table.table-striped.table-hover
      thead
        tr
          th &nbsp;
          th Pack ID
          th Start Date
          th Modified
          th Published
          th Status
          th Quality

      tbody

        tr
          td.bulk-actions colspan="7"

            .btn-group

              a.btn.btn-default.confirm-action href=admin_multi_toggle_published_path data-confirm-msg="Really toggle publishable packs?"
                span Toggle Published

              .btn-group

                button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
                  = image_tag 'icon-drive.png', size: "18x18"
                  = "Sync data "
                  span.caret
                  span.sr-only Toggle Dropdown

                ul.dropdown-menu role="menu"
                  li
                    a.confirm-action href=admin_multi_import_data_path data-confirm-msg="These packs may contain layouts - really sync the data and destroy them?"
                      = "Sync data"
                  li
                    a.selective-sync type="button" data-toggle="modal" data-target="#selective-sync-modal"
                      = "Sync data (SELECTIVE)"

              a.btn.btn-default.confirm-action href=admin_multi_import_images_path data-confirm-msg="Really import images?"
                = image_tag 'icon-dropbox.png', size: "18x18"
                span Sync images


        - if @packs.length > 0
          - @packs.each_with_index do |pack, i|
            tr
              td
                input.bulk-select type="checkbox" name="bulk_id" value=pack.id
              td
                a href=edit_admin_pack_path(id: pack.id)
                  = pack.pack_code
              td= pretty_date(pack.start_date, :month_year)
              td data-timestamp=(pack.modified_at ? pack.modified_at.to_datetime.strftime('%Q') : false)
              td data-timestamp=(pack.published_at ? pack.published_at.to_datetime.strftime('%Q') : false)
              td
                span.label class="label-#{status_class(pack.status)}" = status_human(pack.status)
              td
                .language-quality
                  a.quality-load-link href=admin_pack_get_quality_path(pack_id: pack.id) Reveal


        - else
          tr
            td colspan="7" No packs

- elsif @pack_puzzles

  .asset-thumbnails

    - @pack_puzzles.each do |puzzle|
      = render partial: 'grid_item', locals: {puzzle: puzzle, orderable: true}

= render partial: 'admin/shared/positioner_form'

- if @packs
  = render partial: 'admin/shared/modal_sync'

app/views/admin/packs/new.slim
= form_for [:admin, @pack], html: {}, url: @url do |f|

  div.row.form-actions
    div.col-md-12
      .btn-group
        = f.submit 'Save', class: 'btn btn-default'

        button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
          span.caret
          span.sr-only Toggle Dropdown
          
        ul.dropdown-menu.pull-right role="menu"
          li 
            a.save-edit href="#" Save and Edit
          li
            a href="#{admin_packs_path}" Cancel


  .row.form-group

    .col-sm-6

      .row
        .form-group.col-sm-12
          = f.label :pack_code, class: 'control-label'
          = f.text_field :pack_code, class: 'form-control', disabled: !@pack.new_record?