config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, 
    controllers: { sessions: "admin/sessions" }, 
    path: 'admin', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout'
    }

  scope path: "/(:prefix)", :module => 'admin', :as => 'admin', constraints: { host: UrlHelper.host_constraint(:admin), prefix: 'admin' } do 

    post 'position' => 'application#set_position', as: :set_position
    post 'positions' => 'application#set_positions', as: :set_positions

    resources :puzzles, :path => 'puzzles/pack', except: [:index]
    delete 'puzzles/puzzle_asset/:id', to: 'puzzles#delete_puzzle_asset', as: :delete_puzzle_asset # check this

    resources :languages, except: [:index]
    get 'config' => 'config#index', as: :config
    get 'config/edit/:parameter' => 'config#edit', as: :config_edit
    patch 'config/edit/:parameter' => 'config#update', as: :config_update

    scope :puzzles do

      resources :packs do
        get 'toggle_published' => 'packs#toggle_published', as: :toggle_published
        get 'get_quality' => 'packs#get_quality', as: :get_quality
        get 'import_data/(:mode)' => 'packs#import_data', as: :import_data
        get 'import_images' => 'packs#import_images', as: :import_images
        get 'relink_google_sheet' => 'packs#relink_google_sheet', as: :relink_google_sheet
        get 'ping' => 'packs#check_imports', as: :ping
        get 'info' => 'packs#get_pack_info', as: :info
        get 'restore' => 'packs#restore_from_published', as: :restore_from_published
        resources :puzzle_assets, :path => 'assets', except: [:index]
      end

      scope :packs do
        post '/search' => 'packs#search', as: :search_puzzles
        get '/create_packs/:type/:number' => 'packs#create_packs', as: :create_packs
      end

      get 'puzzle_assets' => 'puzzle_assets#index', as: :puzzle_assets

      get 'generate_sprite_sheets' => 'packs#generate_sprite_sheets', as: :generate_sprite_sheets

      get 'import_data/:puzzle_id/(:mode)' => 'puzzles#import_data', as: :import_puzzle_data

      get 'apitest' => 'api_tester#index', as: :api_test

      post 'move' => 'puzzles#move', as: :puzzle_move

      get 'multi_toggle_published' => 'packs#multi_toggle_published', as: :multi_toggle_published
      get 'multi_import_data' => 'packs#multi_import_data', as: :multi_import_data
      get 'multi_import_images' => 'packs#multi_import_images', as: :multi_import_images

    end

    post 'update_pack' => 'puzzles#create_remote', as: :pack_remote
    post 'update_pack/remove_extras' => 'puzzles#create_remote_and_remove_extras', as: :pack_remote_remove_extras
    post 'update_puzzle' => 'puzzles#create_remote_puzzle', as: :pack_puzzle_remote

    get 'export_answers/:lang/(:pack_type)' => 'puzzles#export_answers', as: :export_answers
    
    get 'job_status/' => 'jobs#index', as: :jobs_status
    
    get '/auth/:provider/callback', to: 'twitter#auth'

    root 'packs#index'

  end

  scope path: "/(:prefix)", constraints: { host: UrlHelper.host_constraint(:data), prefix: 'data' } do 

    get ':api_version/puzzle(.:format)' => 'data#user_generated_puzzle', as: :user_generated_puzzle
    get ':api_version/packs_list(.:format)' => 'data#pack_list', as: :pack_get_list
    get ':api_version/packs_list_chinese(.:format)' => 'data#pack_list_chinese', as: :pack_get_list_chinese
    get ':api_version/packs/puzzle(.:format)' => 'data#pack_puzzle', as: :pack_get_puzzle
    get ':api_version/get_date' => 'data#get_server_date', as: :get_date
    get ':api_version/daily_puzzle(.:format)' => 'data#dailypuzzle', as: :daily_puzzle

  end

  root to: proc { [404, {}, ['']] }

end

app/views/admin/shared/_footer.slim
.modal.fade.asset-modal
  .modal-dialog 
    .modal-content 
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4 class="modal-title"
      .modal-body
        img src=""

footer

app/views/admin/shared/_header.slim
header
  nav.main.navbar.navbar-default
    .container
      .navbar-header
        button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav"
          span class="sr-only" Toggle navigation
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"
        a class="navbar-brand" href="#{admin_root_path}" 
          = image_tag 'icon-wordlaces.png'
          | Word Laces Admin
  
      div id="main-nav" class="collapse navbar-collapse"
        ul class="nav navbar-nav"
          li class="#{ 'active' if params[:controller] == 'admin/packs' }"
            = link_to "Puzzle Packs", admin_packs_path

          li class="#{ 'active' if params[:controller] == 'admin/config' || params[:controller] == 'admin/languages' }"
            = link_to "Config", admin_config_path

          li class="#{ 'active' if params[:controller] == 'admin/api_tester' }"
            = link_to "API Tester", admin_api_test_path

          li class="#{ 'active' if params[:controller] == 'admin/api_tester' }"
            = link_to "Job Status", admin_jobs_status_path

        ul class="nav navbar-nav navbar-right"
          li= link_to 'Log Out', destroy_admin_user_session_path, method: :delete
    
  #breadcrumb
    .container
      ol.breadcrumb
        = render_breadcrumbs tag: :li, separator: ""

  #outputinfo
    .container
      - if @output_info
        .info
          = @output_info
  
  #flash
    - if flash[:errors]
      .errors
        .container
          ul    
            - flash[:errors].each do |error|
              li=error.html_safe
    - if flash[:notices]
      .notice
        .container
          ul    
            - flash[:notices].each do |notice|
              li=notice.html_safe

app/views/admin/shared/_image_panel.slim
- form = local_assigns.fetch :form, nil
- upload_copy = local_assigns.fetch :upload_copy, ''
- zoomable = local_assigns.fetch :zoomable, false

.panel.panel-default.admin-panel.image-panel
  
  - if attachments.length > 1
    .panel-heading
      .btn-group
        - attachments.each do |a|
          - title = a[:title] ? a[:title] : a[:name]
          - a[:styles].each_with_index do |style, index|
            - name = "#{a[:name]}_#{style}"
            button.btn.btn-default type="button" data-attachment="#{a[:name]}" data-variant="#{name}" tab-index="#{index+1}" =title
  
  .panel-body
    - attachments.each do |a|
      - a[:styles].each do |style|
        - name = "#{a[:name]}_#{style}"
        .image data-variant=name class=('zoomable' if zoomable)
          - if image_panel.send(a[:name]).file?
            = image_tag image_panel.send(a[:name], style)
          - else
            = "No image uploaded"

          - if zoomable
            .fa.fa-search-plus.zoom-button

  - if form
    .panel-footer
      - attachments.each do |a|
        - title = a[:title] ? a[:title].titleize : a[:name].titleize
        - upload_copy = a[:upload_copy] ? a[:upload_copy] : ''
        .upload data-attachment="#{a[:name]}"
          = form.label a[:name].to_sym, image_panel.send(a[:name]).file? ? "Update #{title}#{upload_copy}" : "Upload #{title}#{upload_copy}"
          .row 
            .form-group.col-sm-6
              = form.file_field a[:name].to_sym
            - delete = "delete_#{a[:name]}".to_sym
            - if image_panel.respond_to? delete
              .form-group.col-sm-6
                = form.check_box delete
                = " Delete?"

app/views/admin/shared/_modal_sync.slim
- if @pack
  - href = admin_pack_import_data_path(pack_id: @pack.id, mode: 'selective')
- elsif @puzzle
  - href = admin_import_puzzle_data_path(puzzle_id: @puzzle.id, mode: 'selective')
- else
  - href = admin_multi_import_data_path


.modal.fade#selective-sync-modal
  .modal-dialog
    .modal-content

      form.selective-sync-form action=href

        input type="hidden" name="ids" value=""
        
        .modal-header
          button type="button" class="close" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true" &times;
          h4 class="modal-title" Selective Sync
        
        .modal-body

          h4 Sync content

          .radio-inline
            label
              input type="radio" name="content" value="all" checked=('checked' if @sync_prefs && @sync_prefs['content'] == 'all')
              | All data

          .radio-inline
            label
              input type="radio" name="content" value="captions" checked=('checked' if @sync_prefs && @sync_prefs['content'] == 'captions')
              | Only captions

          hr

          h4 Languages

          - @languages.each do |language|
            .checkbox
              label
                input type="checkbox" name="language[]" value=language.code checked=('checked' if @sync_prefs && @sync_prefs['language'].include?(language.code))
                = "#{language.name} (#{language.code})"



        .modal-footer
          button.btn.btn-default.update-selective-sync type="submit" Go

app/views/admin/shared/_multilingual_panel.slim
div.panel.panel-default.admin-panel
  div.panel-heading
    div.btn-group
      - I18n.available_locales.each_with_index do |lang, index|
        button.btn.btn-default type="button" data-variant="#{lang}" tab-index="#{index+1}" =lang
  div.panel-body
    - I18n.available_locales.each_with_index do |lang, index|          
      - value = object.send(field, lang)
      - name = "#{object.class.name.underscore}[#{field}][#{lang}]"
      - id = "#{object.class.name.underscore}_#{field}_#{lang}"
      - data = {variant: "#{lang}"}
      
      - if type == 'textarea'
        = form.text_area field.to_sym, name: name, id: id, value: value, class: 'form-control', data: data
      - else
        = form.text_field field.to_sym, name: name, id: id, value: value, class: 'form-control', data: data

app/views/admin/shared/_pagination.slim
div.paginate
  .row
    .col-md-6.col-md-offset-3
      = paginate pagination

app/views/admin/shared/_positioner_form.slim
form class="position_form_sortable" action=admin_set_positions_path method="post"
  input type="hidden" name="start_index" value=start_index
  input type="hidden" name="positions"
  input type="hidden" name="klass"
  input type="hidden" name="page" value=params[:page]
  input type="hidden" name="authenticity_token" value=form_authenticity_token
  
form class="position_form_select" action=admin_set_position_path method="post"
  input type="hidden" name="id"
  input type="hidden" name="section"
  input type="hidden" name="position"
  input type="hidden" name="klass"
  input type="hidden" name="page" value=params[:page]
  input type="hidden" name="authenticity_token" value=form_authenticity_token

app/views/admin/shared/_sortable_list.slim
- thumbnail_template = local_assigns.fetch :thumbnail_template, false
- item_edit_path = local_assigns.fetch :item_edit_path, false
- item_edit_method = local_assigns.fetch :item_edit_method, false
- add_remove = local_assigns.fetch :add_remove, false
- position_scope_name = local_assigns.fetch :position_scope_name, false
- position_scope = local_assigns.fetch :position_scope, false
- name_field = local_assigns.fetch :name_field, 'name'

- template = (render partial: 'admin/shared/sortable_list_item', locals: {item: template_source, thumbnail_template: thumbnail_template, item_edit_path: item_edit_path, item_edit_method: item_edit_method, add_remove: add_remove, name_field: name_field}).encode

.panel.panel-default.admin-panel.sortable-list data-class=klass.to_s.singularize data-parent=parent data-template=template data-submittable="false"

  .panel-heading

    - if defined? new_item_path
      a.btn.btn-default.pull-right href="#{new_item_path}"
        = "Add #{klass.capitalize}"

    - if add_remove
      .select-list.pull-right
        select.sortable-add-select.form-control
          - addable_items.each do |item|
            - thumbnail = thumbnail_template ? render(partial: thumbnail_template, local: {item: item}) : image_tag(item.thumbnail_image)
            option value=item.id disabled=existing_items.include?(item) data-thumbnail=thumbnail.encode data-caption=item.send(name_field) data-id=item.id
              = item.send(name_field)
        a.btn.btn-default.sortable-add-button href="#"
          = "Add"

  .panel-body
    .row.list.sortable

      .no-items class="#{(existing_items.length > 0) ? 'hide' : ''}"
        = "Nothing to see here"

      - existing_items.each do |item|

        = render partial: 'admin/shared/sortable_list_item', locals: {item: item, thumbnail_template: thumbnail_template, item_edit_path: item_edit_path, item_edit_method: item_edit_method, add_remove: add_remove, name_field: name_field}
  
  
  input.sortable-positions name="#{parent}[#{klass.to_s.singularize}_positions][]" value="" type="hidden"

  - if position_scope
    input name="#{parent}[#{klass.to_s.singularize}_position_scopes][]" value=position_scope type="hidden"

  - if position_scope_name
    input name="#{parent}[#{klass.to_s.singularize}_position_scope_name]" value=position_scope_name type="hidden"
  .sortable-id-list

app/views/admin/shared/_sortable_list_item.slim
.sort-item.col-sm-3.col-md-2 data-id=item.id class="#{item.respond_to?('status') && !item.status ? 'grayed' : ''}"
  
  .thumbnail
    .item-thumbnail
      - thumbnail = thumbnail_template ? render(partial: thumbnail_template, locals: {item: item}) : image_tag(item.thumbnail_image)
      = thumbnail

    .caption
      p.item-caption= item.send(name_field)

      .btn-group

        - if add_remove
          a.btn.btn-default.remove-button type="button" href="#"
            = "Remove"

        - if item_edit_path
          - href = item.new_record? ? item_edit_path : URI::decode(item_edit_path).gsub('[item_id]', item.id.to_s)
        - elsif item_edit_method
          - href = send(item_edit_method, item)
        - else 
          - href = false
        
        - if href
          a.btn.btn-default.edit-button type="button" href=href
            = "Edit"